backend:
  name: git-getway
  branch: master

media_folder: "static/uploads"
public_folder: "uploads"

collections:
  -name : "project_title"
    label: "projects"
    folder: "content/projects" 
    create: true
    slug: "{{year}}-{{month}}-{{slug}}"
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Body", name: "Body", widget: "markdown"}